#!/usr/bin/env bash
set -euo pipefail

DOTNET="${DOTNET:-/usr/local/share/dotnet/x64/dotnet}"
CONTENTLESS_VERSION="4.0.0"

usage() {
  echo "Usage: $0 <ProjectName> [-s Solution.sln]"
  exit 1
}

[[ $# -lt 1 ]] && usage

PROJECT_NAME="$1"; shift
SOLUTION=""

# Parse optional -s Solution.sln
while [[ $# -gt 0 ]]; do
  case "$1" in
    -s|--sln|--solution)
      [[ $# -lt 2 ]] && { echo "Missing value after $1"; exit 1; }
      SOLUTION="$2"; shift 2;;
    *)
      echo "Unknown argument: $1"; usage;;
  esac
done

# Resolve solution choice
if [[ -z "${SOLUTION}" ]]; then
  SLN_COUNT=$(ls -1 *.sln 2>/dev/null | wc -l | tr -d ' ')
  if [[ "$SLN_COUNT" -eq 1 ]]; then
    SOLUTION=$(ls -1 *.sln)
  else
    SOLUTION="2025-Sep-DMIT1514.sln"
  fi
fi

# Create solution if it doesn't exist
if [[ ! -f "${SOLUTION}" ]]; then
  "${DOTNET}" new sln -n "${SOLUTION%.sln}"
fi

# Create project
"${DOTNET}" new mgdesktopgl -n "${PROJECT_NAME}" -o "./${PROJECT_NAME}"

# Add project to solution
"${DOTNET}" sln "${SOLUTION}" add "./${PROJECT_NAME}/${PROJECT_NAME}.csproj"

# Add Contentless package
pushd "./${PROJECT_NAME}" >/dev/null
"${DOTNET}" add package Contentless --version "${CONTENTLESS_VERSION}"

# Ensure Content/Content.mgcb exists
mkdir -p Content
if [[ ! -f Content/Content.mgcb ]]; then
  cat > Content/Content.mgcb <<'EOF'
# Placeholder MGCB file - generated by new-mgproj.sh
EOF
fi

# Insert MonoGameContentReference if missing
CSPROJ="${PROJECT_NAME}.csproj"
if ! grep -q "MonoGameContentReference" "${CSPROJ}"; then
  tmpfile="$(mktemp)"
  awk '
    BEGIN { inserted=0 }
    /<\/Project>/ && inserted==0 {
      print "  <ItemGroup>"
      print "    <MonoGameContentReference Include=\"Content/Content.mgcb\" />"
      print "  </ItemGroup>"
      inserted=1
    }
    { print }
  ' "${CSPROJ}" > "${tmpfile}"
  mv "${tmpfile}" "${CSPROJ}"
fi
popd >/dev/null

# Restore
"${DOTNET}" restore "${SOLUTION}"

echo "✅ Created ${PROJECT_NAME}, added to ${SOLUTION}, Contentless installed, content reference wired, restore complete."
echo "Next:"
echo "  cd \"${PROJECT_NAME}\""
echo "  ${DOTNET} run"